package images.edubiz.src.main.java.model;
// Generated Dec 29, 2011 10:44:56 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Feedback generated by hbm2java
 */
@Entity
@Table(name="feedback"
    ,catalog="edubizforum"
)
public class Feedback  implements java.io.Serializable {


     private Long visitorId;
     private String name;
     private String email;
     private String suggestion;

    public Feedback() {
    }

    public Feedback(String name, String email, String suggestion) {
       this.name = name;
       this.email = email;
       this.suggestion = suggestion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="visitor_id", unique=true, nullable=false)
    public Long getVisitorId() {
        return this.visitorId;
    }
    
    public void setVisitorId(Long visitorId) {
        this.visitorId = visitorId;
    }
    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="email", nullable=false, length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="suggestion", nullable=false, length=200)
    public String getSuggestion() {
        return this.suggestion;
    }
    
    public void setSuggestion(String suggestion) {
        this.suggestion = suggestion;
    }




}


