package images.edubiz.src.main.java.model;
// Generated Dec 29, 2011 10:44:56 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * InternalMsgData generated by hbm2java
 */
@Entity
@Table(name="internal_msg_data"
    ,catalog="edubizforum"
)
public class InternalMsgData  implements java.io.Serializable {


     private Long msgsId;
     private InternalMsg internalMsg;
     private String msgStatus;
     private String msg;

    public InternalMsgData() {
    }

    public InternalMsgData(InternalMsg internalMsg, String msgStatus, String msg) {
       this.internalMsg = internalMsg;
       this.msgStatus = msgStatus;
       this.msg = msg;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="msgs_id", unique=true, nullable=false)
    public Long getMsgsId() {
        return this.msgsId;
    }
    
    public void setMsgsId(Long msgsId) {
        this.msgsId = msgsId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="msg_id", nullable=false)
    public InternalMsg getInternalMsg() {
        return this.internalMsg;
    }
    
    public void setInternalMsg(InternalMsg internalMsg) {
        this.internalMsg = internalMsg;
    }
    
    @Column(name="msg_status", nullable=false, length=10)
    public String getMsgStatus() {
        return this.msgStatus;
    }
    
    public void setMsgStatus(String msgStatus) {
        this.msgStatus = msgStatus;
    }
    
    @Column(name="msg", nullable=false, length=500)
    public String getMsg() {
        return this.msg;
    }
    
    public void setMsg(String msg) {
        this.msg = msg;
    }




}


