package images.edubiz.src.main.java.model;
// Generated Dec 29, 2011 10:44:56 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserRecord generated by hbm2java
 */
@Entity
@Table(name="user_record"
    ,catalog="edubizforum"
)
public class UserRecord  implements java.io.Serializable {


     private String emailId;
     private String userType;
     private String status;
     private Integer newMsg;
     private Integer newForum;
     private Date lastLogin;
     private Set<InternalMsg> internalMsgsForReceiver = new HashSet<InternalMsg>(0);
     private Set<InternalMsg> internalMsgsForSender = new HashSet<InternalMsg>(0);
     private Set<UserDetails> userDetailses = new HashSet<UserDetails>(0);

    public UserRecord() {
    }

	
    public UserRecord(String emailId, String userType, String status, Date lastLogin) {
        this.emailId = emailId;
        this.userType = userType;
        this.status = status;
        this.lastLogin = lastLogin;
    }
    public UserRecord(String emailId, String userType, String status, Integer newMsg, Integer newForum, Date lastLogin, Set<InternalMsg> internalMsgsForReceiver, Set<InternalMsg> internalMsgsForSender, Set<UserDetails> userDetailses) {
       this.emailId = emailId;
       this.userType = userType;
       this.status = status;
       this.newMsg = newMsg;
       this.newForum = newForum;
       this.lastLogin = lastLogin;
       this.internalMsgsForReceiver = internalMsgsForReceiver;
       this.internalMsgsForSender = internalMsgsForSender;
       this.userDetailses = userDetailses;
    }
   
     @Id 
    
    @Column(name="email_id", unique=true, nullable=false, length=50)
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    
    @Column(name="user_type", nullable=false, length=8)
    public String getUserType() {
        return this.userType;
    }
    
    public void setUserType(String userType) {
        this.userType = userType;
    }
    
    @Column(name="status", nullable=false, length=9)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    @Column(name="new_msg")
    public Integer getNewMsg() {
        return this.newMsg;
    }
    
    public void setNewMsg(Integer newMsg) {
        this.newMsg = newMsg;
    }
    
    @Column(name="new_forum")
    public Integer getNewForum() {
        return this.newForum;
    }
    
    public void setNewForum(Integer newForum) {
        this.newForum = newForum;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_login", nullable=false, length=19)
    public Date getLastLogin() {
        return this.lastLogin;
    }
    
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="userRecordByReceiver")
    public Set<InternalMsg> getInternalMsgsForReceiver() {
        return this.internalMsgsForReceiver;
    }
    
    public void setInternalMsgsForReceiver(Set<InternalMsg> internalMsgsForReceiver) {
        this.internalMsgsForReceiver = internalMsgsForReceiver;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="userRecordBySender")
    public Set<InternalMsg> getInternalMsgsForSender() {
        return this.internalMsgsForSender;
    }
    
    public void setInternalMsgsForSender(Set<InternalMsg> internalMsgsForSender) {
        this.internalMsgsForSender = internalMsgsForSender;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="userRecord")
    public Set<UserDetails> getUserDetailses() {
        return this.userDetailses;
    }
    
    public void setUserDetailses(Set<UserDetails> userDetailses) {
        this.userDetailses = userDetailses;
    }




}


