package images.edubiz.src.main.java.model;
// Generated Dec 29, 2011 10:44:56 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserDetails generated by hbm2java
 */
@Entity
@Table(name="user_details"
    ,catalog="edubizforum"
)
public class UserDetails  implements java.io.Serializable {


     private String emailId;
     private UserRecord userRecord;
     private String firstName;
     private String lastName;
     private String address;
     private String city;
     private String postcode;
     private String mobile;
     private String sex;
     private Date dob;
     private String college;
     private String dept;
     private String yaer;
     private Integer confcode;

    public UserDetails() {
    }

	
    public UserDetails(String emailId, UserRecord userRecord, String firstName, String city, String mobile, String college) {
        this.emailId = emailId;
        this.userRecord = userRecord;
        this.firstName = firstName;
        this.city = city;
        this.mobile = mobile;
        this.college = college;
    }
    public UserDetails(String emailId, UserRecord userRecord, String firstName, String lastName, String address, String city, String postcode, String mobile, String sex, Date dob, String college, String dept, String yaer, Integer confcode) {
       this.emailId = emailId;
       this.userRecord = userRecord;
       this.firstName = firstName;
       this.lastName = lastName;
       this.address = address;
       this.city = city;
       this.postcode = postcode;
       this.mobile = mobile;
       this.sex = sex;
       this.dob = dob;
       this.college = college;
       this.dept = dept;
       this.yaer = yaer;
       this.confcode = confcode;
    }
   
     @Id 
    
    @Column(name="email_id", unique=true, nullable=false, length=50)
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="email_id", unique=true, nullable=false, insertable=false, updatable=false)
    public UserRecord getUserRecord() {
        return this.userRecord;
    }
    
    public void setUserRecord(UserRecord userRecord) {
        this.userRecord = userRecord;
    }
    
    @Column(name="first_name", nullable=false, length=50)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    
    @Column(name="last_name", length=50)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    
    @Column(name="address", length=500)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
    @Column(name="city", nullable=false, length=20)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    
    @Column(name="postcode", length=10)
    public String getPostcode() {
        return this.postcode;
    }
    
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }
    
    @Column(name="mobile", nullable=false, length=10)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    
    @Column(name="sex", length=10)
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="dob", length=10)
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    
    @Column(name="college", nullable=false, length=20)
    public String getCollege() {
        return this.college;
    }
    
    public void setCollege(String college) {
        this.college = college;
    }
    
    @Column(name="dept", length=10)
    public String getDept() {
        return this.dept;
    }
    
    public void setDept(String dept) {
        this.dept = dept;
    }
    
    @Column(name="yaer", length=20)
    public String getYaer() {
        return this.yaer;
    }
    
    public void setYaer(String yaer) {
        this.yaer = yaer;
    }
    
    @Column(name="confcode")
    public Integer getConfcode() {
        return this.confcode;
    }
    
    public void setConfcode(Integer confcode) {
        this.confcode = confcode;
    }




}


