package images.edubiz.src.main.java.model;
// Generated Dec 29, 2011 10:44:56 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Visitor generated by hbm2java
 */
@Entity
@Table(name="visitor"
    ,catalog="edubizforum"
)
public class Visitor  implements java.io.Serializable {


     private Long vistorId;
     private String ip;
     private String browser;
     private String os;
     private Date visitTime;

    public Visitor() {
    }

	
    public Visitor(String ip, String browser, String os) {
        this.ip = ip;
        this.browser = browser;
        this.os = os;
    }
    public Visitor(String ip, String browser, String os, Date visitTime) {
       this.ip = ip;
       this.browser = browser;
       this.os = os;
       this.visitTime = visitTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="vistor_id", unique=true, nullable=false)
    public Long getVistorId() {
        return this.vistorId;
    }
    
    public void setVistorId(Long vistorId) {
        this.vistorId = vistorId;
    }
    
    @Column(name="IP", nullable=false, length=20)
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    
    @Column(name="browser", nullable=false, length=20)
    public String getBrowser() {
        return this.browser;
    }
    
    public void setBrowser(String browser) {
        this.browser = browser;
    }
    
    @Column(name="os", nullable=false, length=20)
    public String getOs() {
        return this.os;
    }
    
    public void setOs(String os) {
        this.os = os;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="visit_time", length=19)
    public Date getVisitTime() {
        return this.visitTime;
    }
    
    public void setVisitTime(Date visitTime) {
        this.visitTime = visitTime;
    }




}


