package model;
// Generated Jan 13, 2012 7:18:48 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Feedback generated by hbm2java
 */
public class Feedback  implements java.io.Serializable {


     private Long visitorId;
     private String name;
     private String email;
     private String suggestion;
     private String phone;
     private Date sugDate;
     private String subject;

    public Feedback() {
    }

	
    public Feedback(String name, String email, String suggestion) {
        this.name = name;
        this.email = email;
        this.suggestion = suggestion;
    }
    public Feedback(String name, String email, String suggestion, String phone, Date sugDate, String subject) {
       this.name = name;
       this.email = email;
       this.suggestion = suggestion;
       this.phone = phone;
       this.sugDate = sugDate;
       this.subject = subject;
    }
   
    public Long getVisitorId() {
        return this.visitorId;
    }
    
    public void setVisitorId(Long visitorId) {
        this.visitorId = visitorId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSuggestion() {
        return this.suggestion;
    }
    
    public void setSuggestion(String suggestion) {
        this.suggestion = suggestion;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public Date getSugDate() {
        return this.sugDate;
    }
    
    public void setSugDate(Date sugDate) {
        this.sugDate = sugDate;
    }
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }




}


