package model;
// Generated Jan 13, 2012 7:18:48 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * InternalMsg generated by hbm2java
 */
public class InternalMsg  implements java.io.Serializable {


     private Long msgId;
     private UserRecord userRecordBySender;
     private UserRecord userRecordByReceiver;
     private String msgType;
     private Set<InternalMsgData> internalMsgDatas = new HashSet<InternalMsgData>(0);

    public InternalMsg() {
    }

	
    public InternalMsg(UserRecord userRecordBySender, UserRecord userRecordByReceiver, String msgType) {
        this.userRecordBySender = userRecordBySender;
        this.userRecordByReceiver = userRecordByReceiver;
        this.msgType = msgType;
    }
    public InternalMsg(UserRecord userRecordBySender, UserRecord userRecordByReceiver, String msgType, Set<InternalMsgData> internalMsgDatas) {
       this.userRecordBySender = userRecordBySender;
       this.userRecordByReceiver = userRecordByReceiver;
       this.msgType = msgType;
       this.internalMsgDatas = internalMsgDatas;
    }
   
    public Long getMsgId() {
        return this.msgId;
    }
    
    public void setMsgId(Long msgId) {
        this.msgId = msgId;
    }
    public UserRecord getUserRecordBySender() {
        return this.userRecordBySender;
    }
    
    public void setUserRecordBySender(UserRecord userRecordBySender) {
        this.userRecordBySender = userRecordBySender;
    }
    public UserRecord getUserRecordByReceiver() {
        return this.userRecordByReceiver;
    }
    
    public void setUserRecordByReceiver(UserRecord userRecordByReceiver) {
        this.userRecordByReceiver = userRecordByReceiver;
    }
    public String getMsgType() {
        return this.msgType;
    }
    
    public void setMsgType(String msgType) {
        this.msgType = msgType;
    }
    public Set<InternalMsgData> getInternalMsgDatas() {
        return this.internalMsgDatas;
    }
    
    public void setInternalMsgDatas(Set<InternalMsgData> internalMsgDatas) {
        this.internalMsgDatas = internalMsgDatas;
    }




}


