package model;
// Generated Jan 13, 2012 7:18:48 PM by Hibernate Tools 3.2.1.GA



/**
 * InternalMsgData generated by hbm2java
 */
public class InternalMsgData  implements java.io.Serializable {


     private Long msgsId;
     private InternalMsg internalMsg;
     private String msgStatus;
     private String msg;

    public InternalMsgData() {
    }

    public InternalMsgData(InternalMsg internalMsg, String msgStatus, String msg) {
       this.internalMsg = internalMsg;
       this.msgStatus = msgStatus;
       this.msg = msg;
    }
   
    public Long getMsgsId() {
        return this.msgsId;
    }
    
    public void setMsgsId(Long msgsId) {
        this.msgsId = msgsId;
    }
    public InternalMsg getInternalMsg() {
        return this.internalMsg;
    }
    
    public void setInternalMsg(InternalMsg internalMsg) {
        this.internalMsg = internalMsg;
    }
    public String getMsgStatus() {
        return this.msgStatus;
    }
    
    public void setMsgStatus(String msgStatus) {
        this.msgStatus = msgStatus;
    }
    public String getMsg() {
        return this.msg;
    }
    
    public void setMsg(String msg) {
        this.msg = msg;
    }




}


