package model;
// Generated Jan 13, 2012 7:18:48 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * UserDetails generated by hbm2java
 */
public class UserDetails  implements java.io.Serializable {


     private String emailId;
     private UserRecord userRecord;
     private String firstName;
     private String lastName;
     private String address;
     private String city;
     private String postcode;
     private String mobile;
     private String sex;
     private Date dob;
     private String college;
     private String dept;
     private String yaer;
     private Integer confcode;

    public UserDetails() {
    }

	
    public UserDetails(String emailId, UserRecord userRecord, String firstName, String city, String mobile, String college) {
        this.emailId = emailId;
        this.userRecord = userRecord;
        this.firstName = firstName;
        this.city = city;
        this.mobile = mobile;
        this.college = college;
    }
    public UserDetails(String emailId, UserRecord userRecord, String firstName, String lastName, String address, String city, String postcode, String mobile, String sex, Date dob, String college, String dept, String yaer, Integer confcode) {
       this.emailId = emailId;
       this.userRecord = userRecord;
       this.firstName = firstName;
       this.lastName = lastName;
       this.address = address;
       this.city = city;
       this.postcode = postcode;
       this.mobile = mobile;
       this.sex = sex;
       this.dob = dob;
       this.college = college;
       this.dept = dept;
       this.yaer = yaer;
       this.confcode = confcode;
    }
   
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    public UserRecord getUserRecord() {
        return this.userRecord;
    }
    
    public void setUserRecord(UserRecord userRecord) {
        this.userRecord = userRecord;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getPostcode() {
        return this.postcode;
    }
    
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public String getCollege() {
        return this.college;
    }
    
    public void setCollege(String college) {
        this.college = college;
    }
    public String getDept() {
        return this.dept;
    }
    
    public void setDept(String dept) {
        this.dept = dept;
    }
    public String getYaer() {
        return this.yaer;
    }
    
    public void setYaer(String yaer) {
        this.yaer = yaer;
    }
    public Integer getConfcode() {
        return this.confcode;
    }
    
    public void setConfcode(Integer confcode) {
        this.confcode = confcode;
    }




}


