package model;
// Generated Jan 13, 2012 7:18:48 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Visitor generated by hbm2java
 */
public class Visitor  implements java.io.Serializable {


     private Long vistorId;
     private String ip;
     private String browser;
     private String os;
     private Date visitTime;

    public Visitor() {
    }

	
    public Visitor(String ip, String browser, String os) {
        this.ip = ip;
        this.browser = browser;
        this.os = os;
    }
    public Visitor(String ip, String browser, String os, Date visitTime) {
       this.ip = ip;
       this.browser = browser;
       this.os = os;
       this.visitTime = visitTime;
    }
   
    public Long getVistorId() {
        return this.vistorId;
    }
    
    public void setVistorId(Long vistorId) {
        this.vistorId = vistorId;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public String getBrowser() {
        return this.browser;
    }
    
    public void setBrowser(String browser) {
        this.browser = browser;
    }
    public String getOs() {
        return this.os;
    }
    
    public void setOs(String os) {
        this.os = os;
    }
    public Date getVisitTime() {
        return this.visitTime;
    }
    
    public void setVisitTime(Date visitTime) {
        this.visitTime = visitTime;
    }




}


